In [ ]:
**Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir.
Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 

In [4]:
import numpy as np

numbers = np.array([1,32,548,5,2,90] , dtype=int ) # dtype= str  yaparsan veri tipleri string olur 

In [5]:
numbers

array([  1,  32, 548,   5,   2,  90])

In [80]:
numbers.shape #1 boyurlularda eleman sayısını verir

(6,)

In [32]:
numbers.dtype

dtype('int32')

In [30]:
print(numbers.ndim) # boyut bilgirir

1


In [8]:
print(numbers.size) # eleman sayısı

6


In [ ]:
**İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır.
Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

In [19]:
number2 = np.array([[34,4,78,4],
                    [4,12,3,9]], dtype=int) # farklı veri tipleri ve farklı boyutlarda olmamasına dikkat ediniz

In [33]:
number3 =  np.array([[[1, 2, 3], [4, 5, 6]], 
                     [[1, 2, 3], [4, 5, 6]]])

In [34]:
number3.dtype

dtype('int32')

In [31]:
print("İki boyutlu array de boyut: {} Üç boyutlu array ise: {}".format(number2.ndim,number3.ndim))

İki boyutlu array de boyut: 2 Üç boyutluda array : 3


In [28]:
print("İki boyutlu array de eleman sayısı: {} Üç boyutluda eleman sayısı : {}".format(number2.size,number3.size))

İki boyutlu array de eleman sayısı: 8 Üç boyutluda eleman sayısı : 12


In [35]:
number3.shape # 3 boyutlularda katman,satır ve sütün bilgisini verir

(2, 2, 3)

In [36]:
number2.shape # 2 boyutlu arraylarda satır ve sütün bilgisini verir.

(2, 4)

In [78]:
number2.ndim

2

In [79]:
number3.ndim # 3boyutlu

3

In [37]:
number2[0][1]

4

In [38]:
number2[1][-1]

9

In [39]:
number2[0][2]

78

In [40]:
number3[0][1][2]

6

In [41]:
number3[1]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
number3[1][1][1]

5

Slicing 

In [44]:
number2

array([[34,  4, 78,  4],
       [ 4, 12,  3,  9]])

In [45]:
number3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
#[start:end]
#[start:end:step]

In [48]:
number2[1:]

array([[ 4, 12,  3,  9]])

In [49]:
number2[1:3]

array([[ 4, 12,  3,  9]])

In [55]:
number2[0:1]

array([[34,  4, 78,  4]])

In [57]:
number2[:1]

array([[34,  4, 78,  4]])

In [66]:
number2[0:2,2] 

array([78,  3])

In [81]:
number2[1:,0:2]

array([[ 4, 12]])

In [68]:
number2[: ,1]

array([ 4, 12])

In [70]:
number2[1,:]

array([ 4, 12,  3,  9])

In [71]:
number2[: ,-1]

array([4, 9])

In [58]:
number3[1]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
number3[0,:,1:]

array([[2, 3],
       [5, 6]])

In [75]:
number3[0,1,:]

array([4, 5, 6])

In [76]:
number3[1,1,0:2] # birinci gövdenin içindeki birinci gövde de 0dan başla 2 eleman

array([4, 5])

In [77]:
number3[1,:,0:2] #number3 içinde birinci gövdenin içinden sonuna kadarki içindeki tüm gövdeler de 0dan başla ilk 2 eleman

array([[1, 2],
       [4, 5]])

Reshape : yeniden boyutlandırmak içindir

In [82]:
fruits = np.array(["apple", "banana","grape", "swtrawberry", "watermelon", "blueberry" , "cherry","peach"])

In [83]:
fruits.shape

(8,)

In [85]:
fruits.reshape(4,2)

array([['apple', 'banana'],
       ['grape', 'swtrawberry'],
       ['watermelon', 'blueberry'],
       ['cherry', 'peach']], dtype='<U11')

In [87]:
fruits.reshape(2,4)

array([['apple', 'banana', 'grape', 'swtrawberry'],
       ['watermelon', 'blueberry', 'cherry', 'peach']], dtype='<U11')

In [ ]:
# cannot reshape array of size 8 into shape (5,3) 

In [89]:
fruits.reshape(2,2,2)

array([[['apple', 'banana'],
        ['grape', 'swtrawberry']],

       [['watermelon', 'blueberry'],
        ['cherry', 'peach']]], dtype='<U11')

In [ ]:
#concatenate birleştir

In [93]:
a  = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
np.concatenate([a,a])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [96]:
np.zeros(6) # sıfırlardan oluşan bir array

array([0., 0., 0., 0., 0., 0.])

In [97]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [98]:
np.ones(9,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [99]:
np.ones((3,4) , dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [100]:
np.full((2,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [101]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
#np.arrange(ilkdeğer,sondeğer,sayıaralığı)

In [106]:
np.array(np.linspace(0,1,10))

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [107]:
np.random.randint(6,size=(2,3))

array([[3, 0, 0],
       [5, 4, 5]])

İstatiksel fonksiyonlar

In [109]:
number

[1, 34, 45, 38, 9, 67, 3]

In [112]:
np.max(number)

67

In [113]:
np.min(number)

1

In [114]:
np.mean(number) #ortalama

28.142857142857142

In [115]:
np.std(number) #standartsapma

22.86874705436952

matematiksel fonksiyonlar

In [116]:
number

[1, 34, 45, 38, 9, 67, 3]

In [117]:
numberADD = np.add(number,number)
numberADD

array([  2,  68,  90,  76,  18, 134,   6])

In [ ]:
#np.multiple (çarpma)
#np.divide  (bölme)

 
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
np.dot(a,b)
Çıktı:
array([[19,22],[43,50]])

Matematiksel olarak açılımı:

(1*5)+(2*7)=19
(1*6)+(2*8)=22
(3*5)+(4*7)=43
(3*6)+(4*8)=50
